#
# ======================================================================================
# 实验性多线程编译 Workflow v5 - by Gemini Pro Deep Reasoning
#
# 特性:
# - 基于稳定可靠的 v4 版本。
# - 核心编译步骤采用多线程 (`make -j$(nproc)`) 以大幅缩短编译时间。
# - 保留单线程 (`-j1 V=s`) 作为备用编译选项，提高容错性。
# - 输出的 Artifact 名称明确标识为 "Multi-Thread"，与 v4 版本的产物完全区分。
# - 这是一个独立的 Workflow，可以与 v4 版本同时、并行运行，互不干扰。
#
# 风险提示:
#   在 GitHub Actions 免费的标准 Runner 环境下，多线程编译仍有因内存耗尽 (OOM)
#   而静默失败的风险。此 Workflow 主要用于测试和验证多线程编译的可行性。
# ======================================================================================
#

name: JZ02V10 (v5 - Multi-Thread Experimental)

on:
  # 允许您在 Actions 标签页手动触发此工作流
  workflow_dispatch:
    inputs:
      ssh_action:
        description: '在编译结束后（无论成功或失败），通过 tmate 开启 SSH 会话进行调试。'
        required: false
        default: 'false'

env:
  # 保持与 v4 版本相同的源码和配置
  REPO_URL: https://github.com/lkiuyu/immortalwrt
  REPO_BRANCH: master
  CONFIG_FILE: jz02.config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 1. 检出仓库代码 (Checkout Files)
      uses: actions/checkout@v4

    - name: 2. 准备编译环境 (Initialize Environment & Free Space)
      run: |
        echo "::group::安装核心编译依赖"
        sudo apt-get update
        sudo apt-get install -y build-essential flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git-core libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
        file wget
        echo "::endgroup::"

        echo "::group::清理 Runner 磁盘空间"
        echo "清理前空间:" && df -h
        sudo rm -rf /usr/share/dotnet /opt/ghc "/usr/local/share/boost" "$AGENT_TOOLSDIRECTORY"
        echo "清理后空间:" && df -h
        echo "::endgroup::"
        
        sudo timedatectl set-timezone "$TZ"

    - name: 3. 克隆 ImmortalWrt 源码 (Clone Source)
      run: |
        git clone --depth 1 -b $REPO_BRANCH $REPO_URL openwrt

    - name: 4. 加载自定义内容 (Load Customizations)
      working-directory: ./openwrt
      run: |
        echo "::group::执行自定义脚本 Part 1 (Before Feeds)"
        if [ -f "${{ github.workspace }}/${{ env.DIY_P1_SH }}" ]; then
          chmod +x "${{ github.workspace }}/${{ env.DIY_P1_SH }}"
          "${{ github.workspace }}/${{ env.DIY_P1_SH }}"
        fi
        echo "::endgroup::"

        echo "::group::更新与安装 Feeds"
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        echo "::endgroup::"

        echo "::group::执行自定义脚本 Part 2 (After Feeds)"
        if [ -f "${{ github.workspace }}/${{ env.DIY_P2_SH }}" ]; then
          chmod +x "${{ github.workspace }}/${{ env.DIY_P2_SH }}"
          "${{ github.workspace }}/${{ env.DIY_P2_SH }}"
        fi
        echo "::endgroup::"

    - name: 5. 加载并标准化编译配置 (Load & Finalize Config)
      working-directory: ./openwrt
      run: |
        echo "::group::加载 .config 文件并进行标准化"
        if [ -f "${{ github.workspace }}/${{ env.CONFIG_FILE }}" ]; then
          cp "${{ github.workspace }}/${{ env.CONFIG_FILE }}" .config
        else
          echo "::error::未找到配置文件: ${CONFIG_FILE}！ 编译无法继续。"
          exit 1
        fi
        # 确保 mkbootimg 工具被选中
        echo "CONFIG_PACKAGE_uboot-tools-mkbootimg=y" >> .config
        make defconfig
        echo "配置文件已标准化。"
        echo "::endgroup::"

    - name: 6. 预下载所有软件包源码 (Download Packages)
      working-directory: ./openwrt
      run: |
        echo "::group::开始预下载所有软件包源码"
        make download -j8
        find dl -size -1k -exec rm -f {} \;
        echo "::endgroup::"

    - name: 7. 编译固件 (Compile Firmware - Multi-Thread)
      id: compile
      working-directory: ./openwrt
      run: |
        echo "::group::开始编译固件 (多线程模式, 带单线程备用方案)"
        # 核心修改：使用多线程编译，但保留 V=s 以便在备用方案中获取详细日志
        make -j$(nproc) V=s || make -j1 V=s
        
        if [ $? -ne 0 ]; then
          echo "::error::所有编译尝试均失败！请检查日志以确定问题。"
          exit 1
        fi
        echo "::endgroup::"
        
        echo "status=success" >> $GITHUB_OUTPUT
        echo "FIRMWARE_PATH=$(ls bin/targets/msm89xx/msm8916/*-sysupgrade.bin 2>/dev/null | head -n 1)" >> $GITHUB_ENV

    - name: 8. SSH 远程调试 (按需触发)
      if: (failure() || success()) && inputs.ssh_action == 'true'
      uses: mxschmitt/action-tmate@v3
      with:
        working-directory: ./openwrt

    - name: 9. 整理并上传产物 (Upload Artifacts)
      if: success()
      id: organize
      run: |
        echo "::group::整理并上传固件"
        cd openwrt
        mkdir -p release
        FIRMWARE_PATH="${{ env.FIRMWARE_PATH }}"
        if [ -n "$FIRMWARE_PATH" ]; then
          cp $FIRMWARE_PATH release/
          FACTORY_IMG=$(ls bin/targets/msm8xx/msm8916/*-factory.img 2>/dev/null | head -n 1)
          if [ -n "$FACTORY_IMG" ]; then
            cp $FACTORY_IMG release/
          fi
          cp .config release/config.buildinfo
          sha256sum release/* > release/sha256sums.txt
          echo "FIRMWARE_RELEASE_DIR=$(pwd)/release" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "::error::编译成功但未找到 sysupgrade 文件！"
          find bin/targets -type f
          echo "status=failed" >> $GITHUB_OUTPUT
          exit 1
        fi
        echo "::endgroup::"
      
    - name: 上传到 Actions Artifacts
      if: steps.organize.outputs.status == 'success'
      uses: actions/upload-artifact@v4
      with:
        # 核心修改：修改 Artifact 名称以作区分
        name: ImmortalWrt_Firmware_Multi-Thread_${{ github.run_id }}
        path: ${{ env.FIRMWARE_RELEASE_DIR }}
